period = 1800
allow-ipv6 = true
    
provider ipv6@duckdns.org {
    username        = yourToken
    password        = noPasswordForDuckdns
    hostname        = yourHostname.duckdns.org
    checkip-command = "ip -6 addr show scope global mngtmpaddr | awk -F'[ /]+' '/inet6/{print $3}'"
}

provider ipv6@cloudflare.com {
    username = yourDomain
    password = yourAPIKey
    hostname = yourHostname
    checkip-command = "ip -6 addr show scope global mngtmpaddr | awk -F'[ /]+' '/inet6/{print $3}'"
}
