p script-message cycle-profiles "performance;quality"
q cycle interpolation
Q ignore
Ctrl+j cycle secondary-sid
Ctrl+J cycle secondary-sid down
Ctrl+l script-message load-chat
c cycle video-output-levels
x set sub-delay 0
WHEEL_UP no-osd sub-seek -1
WHEEL_DOWN no-osd sub-seek 1
WHEEL_LEFT seek 5
WHEEL_RIGHT seek -5
[ add speed -0.25
] add speed 0.25
Shift+g add sub-font-size +1
Shift+f add sub-font-size -1
