# Append the following lines to the end of your /etc/pacman.conf
# [options]
# Include = /etc/pacman.conf.d/local-options-and-repos.conf

[options]
Color
VerbosePkgLists
ParallelDownloads = 32
IgnorePkg = 
ILoveCandy

[multilib]
Include = /etc/pacman.d/mirrorlist

[archlinuxcn]
Include = /etc/pacman.d/archlinuxcn-mirrorlist
